### ISSUE TITLE
'socket.gaierror: [Errno -2] Name or service not known' running the example code

### ISSUE THREAD

**Issue by kmille** [joeirimpan/zammad_py#197]
* Zammad API Client version: occurs on [v1.1.0](https://github.com/joeirimpan/zammad_py/releases/tag/v1.1.0) and [v2.0.1](https://github.com/joeirimpan/zammad_py/releases/tag/v2.0.1)
* Python version: 3.10.9
* Operating System: Arch Linux

### Description

I'm having a strange bug. Code:

```python
from zammad_py import ZammadAPI
client = ZammadAPI(url='https://tickets.test.com', username='<USERNAME>', password='<PASSWORD>')
print(client.user.me())
```

Output
```bash
kmille@linbox:zammad-notify poetry run python zammad_notify/zmd.py
my debug output: tickets.test.comusers 443
Traceback (most recent call last):
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x606ede73ea70>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tickets.test.comusers', port=443): Max retries exceeded with url: /me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x606ede73ea70>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kmille/projects/zammad-notify/zammad_notify/zmd.py", line 5, in <module>
    print(client.user.me())
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/zammad_py/api.py", line 396, in me
    response = self._connection.session.get(self.url + "/me")
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='tickets.test.comusers', port=443): Max retries exceeded with url: /me (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x606ede73ea70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
kmille@linbox:zammad-notify 
```

I added  a debug output (in /home/kmille/.cache/pypoetry/virtualenvs/zammad-notify-TBuoGnCs-py3.10/lib/python3.10/site-packages/urllib3/util/connection.py:72)
`my debug output: tickets.test.comusers 443`
So it tries to resolve `tickets.test.comusers ` and that fails.

**Comment by joeirimpan** [comment]
Hi @kmille
From the debug output, it seems like you are missing a trailing forward slash in the url (`tickets.test.com/`).

**Comment by kmille** [comment]
That's super silly on my side. On the other side, some user input validation would be nice. Please check the PR.

Thanks for the quick response!

**Comment by kmille** [comment]
Args, I just realized the user has to specify not only the base url, but even the `/api/v1` must be part of the url ...

**Comment by joeirimpan** [comment]
@kmille Merging this. Thank you (y)
