### ISSUE TITLE
Self Signed SSL Certificate verification not skippable

### ISSUE THREAD

**Issue by antonionardella** [joeirimpan/zammad_py#238]
* Zammad API Client version: 3.0.0
* Python version: 3.11.2
* Operating System: Debian 12

### Description

I tried the example on a self hosted test instance and since it is using a self signed certificate the module gave the error that certificate validation failed.

To solve this it would be great to be able to give a parameter like `skip_ssl_verification=True`
Example usage: `client = ZammadAPI(url=domain_url, http_token=token, skip_ssl_verification=True)`

### What I Did
```
from zammad_py import ZammadAPI
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Read domain URL, SSL verification, and token from environment variables
domain_url = os.getenv('API_DOMAIN_URL')
token = os.getenv('API_TOKEN')

client = ZammadAPI(url=domain_url, http_token=token)

# Example: Create a group
params = {
    "name": "ABCD",
    "signature_id": None,
    "email_address_id": None,
    "assignment_timeout": None,
    "follow_up_possible": "yes",
    "follow_up_assignment": True,
    "active": True,
    "note": "zammad_py",
    "lasis_code": None
}
new_group = client.group.create(params=params)
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antonio/dev/zammad/tools/API_imports/import_tool.py", line 29, in <module>
    new_group = client.group.create(params=params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonio/dev/zammad/tools/API_imports/venv/lib/python3.11/site-packages/zammad_py/api.py", line 280, in create
    response = self._connection.session.post(self.url, json=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonio/dev/zammad/tools/API_imports/venv/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonio/dev/zammad/tools/API_imports/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonio/dev/zammad/tools/API_imports/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antonio/dev/zammad/tools/API_imports/venv/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.0.10.65', port=443): Max retries exceeded with url: /api/v1/groups (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:992)')))
```

Thank you!

**Comment by antonionardella** [comment]
Duplicate of https://github.com/joeirimpan/zammad_py/issues/206

Sorry, did not see it
